name: Weekly-update

on:
  workflow_dispatch:
  schedule:
      - cron: '0 11 * * 5' 
#     - cron: '0 0 * * 0' # once a week on Sunday at 5:00PM PST/ 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.API_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
