name: Weekly-update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # once a week on Sunday at 5:00PM PST/ 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: GitHub Config
        run: |
          git config --global user.email "huycnguyen2020@gmail.com"
          git config --global user.name "Huy Nguyen"
      - name: Setup Node.js  
        uses: actions/setup-node@v3
      - name: Install libraries
        run: npm ci
      - name: npm run deploy
        run: npm run deploy:ci
