name: Weekly-update

on:
  workflow_dispatch:
  schedule:
      - cron: '0 11 * * 5' 
#     - cron: '0 0 * * 0' # once a week on Sunday at 5:00PM PST/ 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node.js  
        uses: actions/setup-node@v3
        with:
          node-version: 16.8.x
          cache: npm
      - name: npm run deploy
        run: npm run deploy
